# 设置默认编码
export LANG=en_US.UTF-8
export LC_ALL=$LANG

# 设置默认编辑器，打命令的时候试试 C-x C-e
export EDITOR=vim

# 允许在交互模式中使用注释  例如：
#     cmd... # 这是注释
setopt INTERACTIVE_COMMENTS

# 启用自动 cd，输入目录名回车进入目录
# 稍微有点混乱，不如 cd 补全实用
# setopt AUTO_CD

# 不要蜂鸣警报 beep
setopt NO_BEEP

# 禁用 core dumps
limit coredumpsize 0

# 以下字符视为单词的一部分
# http://zsh.sourceforge.net/Guide/zshguide04.html#4.3.4
# 默认值：*?_-.[]~=/&;!#$%^(){}<>
WORDCHARS=${WORDCHARS//[\/_&.;]}

# 行编辑高亮模式
# Ctrl+@ 设置标记，标记和光标点之间为 region
zle_highlight=(region:bg=magenta  # 选中区域
               special:bold       # 特殊字符
               isearch:underline) #搜索时使用的关键字

# 路径别名
# 进入相应的路径时只要 cd ~xxx
hash -d E="/etc/env.d"
hash -d C="/etc/conf.d"
hash -d R="/etc/rc.d"
hash -d EM="$HOME/.emacsrc"

export ZSH=$HOME/dotfiles/zshfiles

for file in theme history command directories auto_complete key_binding zplug; do
  ZSH=$HOME/dotfiles/zshfiles
  source $ZSH/$file.zsh
done

export ZSH=$HOME/dotfiles/zshfiles
